# 공통

server:
  port: 8084

fcm:
  keypath: ./alarm-1830c-firebase-adminsdk-vbgdk-636d5e3a1c.json

redis-key-prefix: 'noti:'

spring:
  profiles:
    active: local   # 프로파일 지정 없으면 디폴트로 local 사용
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
  #    아래 선언시 -> 구동시 ddl create, 종료시 ddl drop
  #    hibernate:
  #      ddl-auto: update

---

# 로컬 IDE기반 개발용 프로파일
spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mariadb://localhost:3306/test

---

# 로컬에서 도커로 띄워놓을때 사용하는 프로파일
spring:
  config:
    activate:
      on-profile: local-docker
  redis:
    host: host.docker.internal
    port: 6379
  datasource:
    url: jdbc:mariadb://host.docker.internal:3306/test
